### PR TITLE
Introduce t_guest_mprotect() in ELF loader, fix hvt implementation

### LINKED ISSUE #390: hvt: Guest-executable pages should not be marked PROT_EXEC on the host
During discussion of interaction between host `mprotect()` and KVM behaviour, Sean Christopherson [pointed out to me](https://marc.info/?l=kvm&m=155872602111445&w=2) that our current implementation results in guest-executable pages also being executable on the host side. This is a security issue, since were the hvt tender compromised, it would make it much easier for an attacker to execute code in the tender process.

### PR DESCRIPTION
**Pull request by mato**
This allows for tender (spt, hvt) control over how page protection is applied to guest memory. This infrastructure is then used to ensure that guest-executable pages are not also host-executable.

See individual commits for details.

Fixes #390.

/cc @cfcs #370 #303

### CODE REVIEW

File: tenders/common/elf.c [hunk 1]
```diff
@@ -194,7 +195,8 @@ static int align_up(Elf64_Addr addr, Elf64_Xword align, Elf64_Addr *out_result)
 }
 
 void elf_load(int bin_fd, const char *bin_name, uint8_t *mem, size_t mem_size,
-       uint64_t p_min_loadaddr, uint64_t *p_entry, uint64_t *p_end)
+        uint64_t p_min_loadaddr, guest_mprotect_fn_t t_guest_mprotect, void *t,
```
Comment (cfcs) [inline tenders/common/elf.c]: 1) Hmm, would you be okay with changing the name to be something a bit more specific, like `void *tender_handle`
 or `*t_guest_mprotect_handle` whatever that is easier to recognize at the call site of `t_guest_mprotect()`?

2) Later on this will be casted to one of:
    ```c
    struct hvt *hvt = t;
    struct spt *spt = t;
    ```
    I wonder if it would make sense with a target-specific pointer type so we avoid having `void *` casts passed around?

File: tenders/common/elf.h [hunk 2]
```diff
@@ -25,10 +25,22 @@
...
+ * guest_mprotect_fn() is called by the ELF loader to request that the page
+ * protection flags (prot) as used by the system mprotect(), i.e. PROT_X from
+ * sys/mman.h be applied to the guest memory range (addr_start .. addr_end).
+ * (t) is the backend-specific argument.
+ *
+ * Returns 0 on success, -1 and errno set on failure.
+ */
+typedef int (*guest_mprotect_fn_t)(void *t, uint64_t addr_start,
+        uint64_t addr_end, int prot);
+
```
Comment (cfcs) [inline tenders/common/elf.h]: This lacks a description of `t` (see previous comment).

File: tenders/hvt/hvt.h [hunk 3]
```diff
@@ -107,6 +107,13 @@ void hvt_vcpu_init(struct hvt *hvt, hvt_gpa_t gpa_ep);
 void hvt_boot_info_init(struct hvt *hvt, hvt_gpa_t gpa_kend, int cmdline_argc,
         char **cmdline_argv, struct mft *mft, size_t mft_size);
 
+/*
+ * Apply page protections to guest memory. See guest_mprotect_fn_t in elf.h for
+ * a full description.
+ */
+int hvt_guest_mprotect(void *t, uint64_t addr_start, uint64_t addr_end,
```
Comment (cfcs) [inline tenders/hvt/hvt.h]: Would it be tricky to just do `struct hvt *t` directly?
```suggestion
int hvt_guest_mprotect(struct hvt *t, uint64_t addr_start, uint64_t addr_end,
```

Comment (cfcs) [reply tenders/hvt/hvt.h]: It seems like `addr_start` and `addr_end` could additionally be const? (To decrease risk of confusing `vaddr_start` and `addr_start` when the former is assigned)

File: tenders/spt/spt_core.c [hunk 4]
```diff
@@ -146,6 +146,28 @@ struct spt *spt_init(size_t mem_size)
...
+    assert(vaddr_start >= spt->mem);
+    size_t size = addr_end - addr_start;
+    assert(size > 0 && size <= spt->mem_size);
+
+    /*
+     * On spt, there is no distinction between host-side and guest-side memory
+     * protection, so just pass through to mprotect() directly, which will do
+     * the right thing.
+     */
+    return mprotect(vaddr_start, size, prot);
```
Comment (cfcs) [inline tenders/spt/spt_core.c]: Do we have use-cases for `W && X` mappings, or would it make sense to prevent the creation of such mappings?

File: tenders/common/elf.h (hunk 2 above)
Comment (cfcs) [reply tenders/common/elf.h]: It it correctly understood that in most cases `guest_mprotect_fn_t` primarily applies memory protection flags to the *host* view of the guest's memory mappings?

File: tenders/common/elf.c (hunk 1 above)
Comment (mato) [reply tenders/common/elf.c]: 1. I can do `void *t_guest_mprotect_arg`.
2. Will reply separately re function pointers.

File: tenders/common/elf.h (hunk 2 above)
Comment (mato) [reply tenders/common/elf.h]: > This lacks a description of t (see previous comment).

That's because I don't know what to call `t` in prose. "core tender struct" doesn't add any information.

> It it correctly understood that in most cases guest_mprotect_fn_t primarily applies memory protection flags to the host view of the guest's memory mappings?

Not quite. On KVM, at least the R/W part of the flags is applied also (indirectly) to the _guest_ mappings. On OpenBSD, if at some point if `vmm` gains support for `VMM_IOC_MPROTECT_EPT` then this function will also be responsible for directly manipulating the guest mappings via EPT.

File: tenders/hvt/hvt.h (hunk 3 above)
Comment (mato) [reply tenders/hvt/hvt.h]: > It seems like addr_start and addr_end could additionally be const? (To decrease risk of confusing vaddr_start and addr_start when the former is assigned)

That doesn't work well in C for primitive types, since if you have e.g.

    int foo(const int bar);

then whatever `int` the _caller_ passed to `foo()` must also be `const` on the caller's side. So it's not very practical. Not worth it here.

File: tenders/spt/spt_core.c (hunk 4 above)
Comment (mato) [reply tenders/spt/spt_core.c]: > Do we have use-cases for W && X mappings, or would it make sense to prevent the creation of such mappings?

Already done by the caller (ELF loader) at https://github.com/Solo5/solo5/blob/master/tenders/common/elf.c#L344, I don't want to do that check here.

**Comment by mato** [comment]
> I wonder if there's a not-overly-complex way to avoid function pointers being passed around; they constitute a natural target for ROP-style exploits and pose challenges for control-flow integrity systems.

I agree that fiunction pointers are not great for the reasons you mention, but I don't see a way around them.

We're trying to keep the ELF loader decoupled from other code, and remember it's shared between different tenders, so the function has different types, expecting a `struct hvt` or `struct spt` depending on the tender.

> 1. I guess one option could be to write tuples of (`prot, addr_start , addr_end`) somewhere from `elf_load` and have a specialized `elf_load` wrapper for each target that looped over that list and applied the protections, but I'm not sure that's cleaner.

That's more code and passing data around, likely more complexity and bugs.

> 2. Another option could be to merge this as-is, and keep it in mind for any future restructuring of these things that we end up doing. Without a good solution I feel that is probably the way to go, but I wanted to leave my concern here in case you had a good idea for how to avoid the function pointer.

I prefer to merge and get the fix, rather than trying to find "clever" ways of avoiding the function pointer now. However, for the record, there is a third option:

We could use preprocessor magic and make the decision on what to call at compile time, thus avoiding the function pointer. However, we still have the issue of the argument `t_guest_mprotect_arg` which needs to be passed through `elf_load()`. So there would be quite a bit of `#ifdef` magic around _and_ in order to get the build system to grok different `elf.o`'s for hvt and spt, we would also have to `#include "../common/elf.c"` into a different module. So, doable, but not exactly the least-surprising way to do things.

File: tenders/spt/spt_core.c (hunk 4 above)
Comment (cfcs) [reply tenders/spt/spt_core.c]: Ah, I had missed that that took place just above the call site in `elf_load`.

File: tenders/common/elf.h (hunk 2 above)
Comment (cfcs) [reply tenders/common/elf.h]: `t_arg` is fine with me, it's easier to search for and harder to confuse than `t`.

**Comment by cfcs** [comment]
Cool, thanks for answering my questions. I say LGTM then :)
