### PR TITLE
ELF loader audit

### LINKED ISSUE #126: ukvm: Multiple issues with ELF loader
While reviewing #123 and trying to write a test to go into `tests/` for #73 I found (at least) the following issues with the ELF loader in ukvm:

1. In `load_code()` the test for a loadable segment is incorrect, `phdr.p_type` is not a bitmap.
2. Return values from `mprotect()` are not checked.
3. The `mprotect()` call which is supposed to write-protect `.text` is passed a `len` which is not a multiple of the page size.
4. (related) Trying to write to a global `char *` in the guest produces an `EFAULT` exit from `KVM_RUN` where it should succeed.

I'm working on auditing that code and fixing the above.

### PR DESCRIPTION
**Pull request by mato**
Fixes #126. See individual commits for details.

@djwillia Please review.

### CODE REVIEW

File: ukvm/ukvm-core.c [hunk 1]
```diff
@@ -224,45 +224,55 @@ static void load_code(const char *file, uint8_t *mem,     /* IN */
...
-        /* Protect the executable code */
-        if (phdr[ph_i].p_flags & PF_X)
-            mprotect((void *) dst, memsz, PROT_EXEC | PROT_READ);
 
+        if ((paddr >= GUEST_SIZE) || add_overflow(paddr, filesz, result) ||
+            (result >= GUEST_SIZE)) {
+            errx(1, "%s: Invalid segment: paddr=0x%" PRIx64 ", filesz=%zu",
+                    file, paddr, filesz);
+        }
+        if (add_overflow(paddr, memsz, result) || (result >= GUEST_SIZE)) {
```
Comment (ricarkol) [inline ukvm/ukvm-core.c]: I'm not 100% sure this can't overflow after the ALIGN_UP below. It doesn't seem to because (but wanted to double check with you): if `(paddr_memsz <= 1e64)` then `ALIGN_UP(paddr+memsz, 4096) <= 1e64`. And that will be true if paddr and memsz are both `uint64_t` so `add_overflow` becomes `UaddLL_overflow`, and if the check is `<=` and not `<`. Wouldn't it be safer to make memsz an uint64_t just to be sure the correct add_overflow is used?

`(result >= GUEST_SIZE)` is not needed here as that check is done one line below.

Comment (mato) [inline ukvm/ukvm-core.c]: >  if (paddr_memsz <= 2^64) then ALIGN_UP(paddr+memsz, 4096) <= 2^64
I don't follow. `align` comes from the ELF file, so we can't make any assumptions about its value.

Regarding using an `uint64_t` for `memsz`, that shouldn't matter as `paddr` and `result` are already both `uint64_t`, so the result will be computed using the correct types (see #117, #126) If I've got that behaviour wrong then #126 is also wrong :-/.

The `(result -> GUEST_SIZE)` check is just to trigger the correct error message about `memsz` being invalid rather than `_end`. I can simplify a bit more and do this (re-use `result`):

````
    if ((paddr >= GUEST_SIZE) || add_overflow(paddr, filesz, result) ||
        (result >= GUEST_SIZE)) {
        /* ... complain about filesz */
    }
    if (add_overflow(paddr, memsz, result) || (result >= GUEST_SIZE)) {
        /* ... complain about memsz */
    }
    _end = ALIGN_UP(result, align);
    if (_end >= GUEST_SIZE) {
    /* ... complain about _end */
    }
````

What do you think?

Comment (ricarkol) [inline ukvm/ukvm-core.c]: Looks good, mainly wanted to double check and have a full understanding of it. All makes sense, thanks!

Comment (ricarkol) [inline ukvm/ukvm-core.c]: `if (paddr_memsz <= 2^64) then ALIGN_UP(paddr+memsz, ALIGN) <= 2^64` is true as long as 2^64 is a multiple of ALIGN. Which I'm guess is the case, as ALIGN seems to always be 4096.

Comment (mato) [inline ukvm/ukvm-core.c]: That's true, but the point of these checks is that the data in the ELF file is supplied by the guest, so could be crafted to be malicious. So a little extra paranoia can't hurt.

Comment (mato) [inline ukvm/ukvm-core.c]: See f47d93b, that replaces ALIGN_UP with a bitwise operation and addresses the case where it's not a power of 2 by just ignoring the value.

**Comment by ricarkol** [comment]
Hi Mato, there's still a problem. `2**64` is still overflowing: max_value(uint64_t) is 0xffffffffffffffff and not 0x1000000000000), so even if align is a power of two, we will overflow. For example, if align=4096 and `paddr+memsz=0xffffffffffffffff-100`, then result will be 0.

```#include <stdio.h>

int main()
{
        unsigned long long align = 4096;
        unsigned long long result = 0xffffffffffffffff - 100;
        printf("%llx\n", (result + (align - 1)) & -align);
}
```
===> outputs 0

**Comment by mato** [comment]
(copying comments from Slack, for the record)

I realise the `﻿⁠⁠⁠⁠(x + (a -1 )) & -a)`﻿⁠⁠⁠⁠ computation can overflow, however if it overflows into anything _﻿⁠⁠dangerous﻿⁠_⁠ it'll get caught by the check here: https://github.com/Solo5/solo5/blob/master/ukvm/ukvm-core.c#L260.

If the final value of `_end` is bogus but not dangerous, we don't care (garbage in, garbage out!).

**Comment by mato** [comment]
(After further discussion.) There is still an edge case here. The guest could potentially supply a value of ﻿⁠⁠⁠⁠align﻿⁠⁠⁠⁠ that would overflow in such a way that (for example) ﻿⁠⁠⁠⁠_end == paddr﻿⁠⁠⁠⁠ rendering the following call to ﻿⁠⁠⁠⁠mprotect()﻿⁠⁠⁠⁠ useless. So the code really needs to use `add_overflow()` for the alignment computation as well.

**Comment by mato** [comment]
Reopened #126 so that I don't forget to address this last point.

**Comment by mato** [comment]
@ricarkol Addressed in #129, take a look.
